import Link from 'next/link';
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import hMenuStyle from 'src/styles/Header.module.css'
import { ReactNode, useEffect, useState } from 'react';
// import classNames from 'classnames';
// import sMenuStyle from '@/styles/Sidebar.module.css'
// import PropTypes from 'prop-types'

const AppLayout = ({ children }: { children: ReactNode }): JSX.Element => {

    const [isLogin, setIsLogin] = useState<boolean>(false);

    useEffect(() => {
        setIsLogin((sessionStorage.getItem(process.env.NEXT_PUBLIC_ACCESS_TOKEN ?? "") ?? "").length > 0);
    }, [])
    return (
        <div className={styles.container}>
            <Head>
                <title>My next app</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                {/* <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&display=swap" rel="stylesheet" />
                <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" /> */}
            </Head>

            {/* <div className="menu">
                <label htmlFor="expand-menu"><div>메뉴</div></label>
                <input type="checkbox" id="expand-menu" name="expand-menu" />
                    <ul>
                        <li><a href="#" className="item"><div>프로필</div></a></li>
                        <li><a href="#" className="item"><div>데이터사용량</div></a></li>
                        <li><a href="#" className="item"><div>내URL</div></a></li>
                        <li><a href="#" className="item"><div>구매내역</div></a></li>
                        <li><a href="#" className="item"><div>추천목록</div></a></li>
                        <li><a href="#" className="item"><div>설정</div></a></li>
                    </ul>
            </div> */}

            <header>
                <section className={hMenuStyle.hbody}>
                    <nav className={hMenuStyle.nav}>
                        <div className={hMenuStyle.title}><Link href="/">DJK</Link></div>
                        <ul className={hMenuStyle.menu}>
                            <li><Link href="/">home</Link></li>
                            <li><Link href="/git-test/Hello">Hello</Link></li>
                            <li><Link href="/jquery">jQuery</Link></li>
                            <li><Link href="/kakao">kakao</Link></li>
                            <li><Link href="/toDoList">todoList</Link></li>
                            {isLogin
                                ? (
                                    <li><Link href="/logout">Logout</Link></li>
                                )
                                : (
                                    <li><Link href="/login/loginProcess">Login</Link></li>
                                )
                            }
                        </ul>
                        <i className={[hMenuStyle.fab, hMenuStyle.fa_twitter_squar].join(' ')}></i>
                        <i className={[hMenuStyle.fas, hMenuStyle.fa_bars].join(' ')}></i>
                    </nav>
                </section>
            </header>
            <main style={{ padding: '70px 50px' }}>{children}</main>
            <footer className="footer">
            </footer>
        </div>
    )
}

// AppLayout.PropTypes = {
//     children: PropTypes.node.isRequired
// }

export default AppLayout