import Link from 'next/link';
import Head from 'next/head'
import styles from '/src/styles/Home.module.css'
// import PropTypes from 'prop-types'

const AppLayout = ({ children }: any) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <section className="hbody">
                    <article className="nav">
                        <div className="title"><Link href="/">DJK</Link></div>
                        <ul id="menu">
                            <li><Link href="/">home</Link></li>
                            <li><Link href="/git-test/About">About</Link></li>
                            <li><Link href="/git-test/Hello">Hello</Link></li>
                            <li><Link href="/jquery">jQuery</Link></li>
                            <li><Link href="/kakao">kakao</Link></li>
                            <li><Link href="/toDoList">todoList</Link></li>
                        </ul>
                        <i className="fab fa-twitter-square"></i>
                        <i className="fas fa-bars"></i>
                    </article>
                </section>
            </header>
            <main>{children}</main>
            <footer className="footer">
            </footer>
        </div>
    )
}

// AppLayout.PropTypes = {
//     children: PropTypes.node.isRequired
// }

export default AppLayout